$managedDatablockSet = new SimSet() {
   canSaveDynamicFields = "1";
      setType = "Datablocks";
	  
   new t2dImageMapDatablock(char_tourist_angerImageMap) {
      imageName = "~/data/images/char_tourist_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_tourist_approveImageMap) {
      imageName = "~/data/images/char_tourist_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_tourist_drinkImageMap) {
      imageName = "~/data/images/char_tourist_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_tourist_idleImageMap) {
      imageName = "~/data/images/char_tourist_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_tourist_angerAnimation) {
      imageMap = "char_tourist_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_tourist_approveAnimation) {
      imageMap = "char_tourist_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_tourist_drinkAnimation) {
      imageMap = "char_tourist_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_tourist_idleAnimation) {
      imageMap = "char_tourist_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(char_hawaiiwarrior_angerImageMap) {
      imageName = "~/data/images/char_hawaiiwarrior_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_hawaiiwarrior_approveImageMap) {
      imageName = "~/data/images/char_hawaiiwarrior_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_hawaiiwarrior_drinkImageMap) {
      imageName = "~/data/images/char_hawaiiwarrior_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_hawaiiwarrior_idleImageMap) {
      imageName = "~/data/images/char_hawaiiwarrior_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_tiki_angerImageMap) {
      imageName = "~/data/images/char_tiki_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_tiki_approveImageMap) {
      imageName = "~/data/images/char_tiki_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_tiki_drinkImageMap) {
      imageName = "~/data/images/char_tiki_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_tiki_idleImageMap) {
      imageName = "~/data/images/char_tiki_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_hawaiiwarrior_angerAnimation) {
      imageMap = "char_hawaiiwarrior_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_hawaiiwarrior_approveAnimation) {
      imageMap = "char_hawaiiwarrior_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_hawaiiwarrior_drinkAnimation) {
      imageMap = "char_hawaiiwarrior_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_hawaiiwarrior_idleAnimation) {
      imageMap = "char_hawaiiwarrior_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_tiki_angerAnimation) {
      imageMap = "char_tiki_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_tiki_approveAnimation) {
      imageMap = "char_tiki_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_tiki_drinkAnimation) {
      imageMap = "char_tiki_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_tiki_idleAnimation) {
      imageMap = "char_tiki_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };

   new t2dImageMapDatablock(shorebreakImageMap) {
      imageName = "~/data/images/shorebreak.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_hulagirl3_angerImageMap) {
      imageName = "~/data/images/char_hulagirl3_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_hulagirl3_approveImageMap) {
      imageName = "~/data/images/char_hulagirl3_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_hulagirl3_drinkImageMap) {
      imageName = "~/data/images/char_hulagirl3_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_hulagirl3_idleImageMap) {
      imageName = "~/data/images/char_hulagirl3_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_hulagirl3_angerAnimation) {
      imageMap = "char_hulagirl3_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_hulagirl3_approveAnimation) {
      imageMap = "char_hulagirl3_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_hulagirl3_drinkAnimation) {
      imageMap = "char_hulagirl3_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_hulagirl3_idleAnimation) {
      imageMap = "char_hulagirl3_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };   
   new t2dImageMapDatablock(hula_dancer3ImageMap) {
      imageName = "~/data/images/hula_dancer3.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "4";
      cellCountY = "5";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(hula_dancer3Animation) {
      imageMap = "hula_dancer3ImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19";
      animationTime = "1.66667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };   
   new t2dImageMapDatablock(char_elvis_angerImageMap) {
      imageName = "~/data/images/char_elvis_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_elvis_approveImageMap) {
      imageName = "~/data/images/char_elvis_approve.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_elvis_drinkImageMap) {
      imageName = "~/data/images/char_elvis_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_elvis_idleImageMap) {
      imageName = "~/data/images/char_elvis_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_elvis_angerAnimation) {
      imageMap = "char_elvis_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_elvis_approveAnimation) {
      imageMap = "char_elvis_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_elvis_drinkAnimation) {
      imageMap = "char_elvis_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_elvis_idleAnimation) {
      imageMap = "char_elvis_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(bkgd_hawaii_finalImageMap) {
      imageName = "~/data/images/bkgd_hawaii_final.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };   
};