$managedDatablockSet = new SimSet() {
   canSaveDynamicFields = "1";
      setType = "Datablocks";
	  
   new t2dImageMapDatablock(char_housewife_angerImageMap) {
      imageName = "~/data/images/char_housewife_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_housewife_approveImageMap) {
      imageName = "~/data/images/char_housewife_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_housewife_drinkImageMap) {
      imageName = "~/data/images/char_housewife_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_housewife_idleImageMap) {
      imageName = "~/data/images/char_housewife_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_poodlegirl_angerImageMap) {
      imageName = "~/data/images/char_poodlegirl_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_poodlegirl_approveImageMap) {
      imageName = "~/data/images/char_poodlegirl_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_poodlegirl_drinkImageMap) {
      imageName = "~/data/images/char_poodlegirl_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_poodlegirl_idleImageMap) {
      imageName = "~/data/images/char_poodlegirl_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_housewife_angerAnimation) {
      imageMap = "char_housewife_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_housewife_approveAnimation) {
      imageMap = "char_housewife_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_housewife_drinkAnimation) {
      imageMap = "char_housewife_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_housewife_idleAnimation) {
      imageMap = "char_housewife_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_poodlegirl_angerAnimation) {
      imageMap = "char_poodlegirl_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_poodlegirl_approveAnimation) {
      imageMap = "char_poodlegirl_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_poodlegirl_drinkAnimation) {
      imageMap = "char_poodlegirl_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_poodlegirl_idleAnimation) {
      imageMap = "char_poodlegirl_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(char_greaser_angerImageMap) {
      imageName = "~/data/images/char_greaser_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_greaser_approveImageMap) {
      imageName = "~/data/images/char_greaser_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_greaser_drinkImageMap) {
      imageName = "~/data/images/char_greaser_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_greaser_idleImageMap) {
      imageName = "~/data/images/char_greaser_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_jock_angerImageMap) {
      imageName = "~/data/images/char_jock_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_jock_approveImageMap) {
      imageName = "~/data/images/char_jock_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_jock_drinkImageMap) {
      imageName = "~/data/images/char_jock_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_jock_idleImageMap) {
      imageName = "~/data/images/char_jock_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_greaser_angerAnimation) {
      imageMap = "char_greaser_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_greaser_approveAnimation) {
      imageMap = "char_greaser_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_greaser_drinkAnimation) {
      imageMap = "char_greaser_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_greaser_idleAnimation) {
      imageMap = "char_greaser_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_jock_angerAnimation) {
      imageMap = "char_jock_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_jock_approveAnimation) {
      imageMap = "char_jock_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_jock_drinkAnimation) {
      imageMap = "char_jock_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_jock_idleAnimation) {
      imageMap = "char_jock_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };   
   new t2dImageMapDatablock(char_mayor_angerImageMap) {
      imageName = "~/data/images/char_mayor_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_mayor_approveImageMap) {
      imageName = "~/data/images/char_mayor_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_mayor_drinkImageMap) {
      imageName = "~/data/images/char_mayor_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_mayor_idleImageMap) {
      imageName = "~/data/images/char_mayor_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };

   new t2dAnimationDatablock(char_mayor_angerAnimation) {
      imageMap = "char_mayor_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_mayor_approveAnimation) {
      imageMap = "char_mayor_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_mayor_drinkAnimation) {
      imageMap = "char_mayor_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_mayor_idleAnimation) {
      imageMap = "char_mayor_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };

   new t2dImageMapDatablock(fx_jukeboxImageMap) {
      imageName = "~/data/images/fx_jukebox.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "5";
      cellCountY = "1";
      cellWidth = "79";
      cellHeight = "116";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(fx_neon1ImageMap) {
      imageName = "~/data/images/fx_neon1.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "5";
      cellCountY = "1";
      cellWidth = "65";
      cellHeight = "68";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(fx_sodaftn_castlightImageMap) {
      imageName = "~/data/images/fx_sodaftn_castlight.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(fx_jukeboxAnimation) {
      imageMap = "fx_jukeboxImageMap";
      animationFrames = "0 1 2 3 4";
      animationTime = "0.833333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(fx_neon1Animation) {
      imageMap = "fx_neon1ImageMap";
      animationFrames = "0 1 2 3 4";
      animationTime = "0.833333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(greaser_lean2ImageMap) {
      imageName = "~/data/images/greaser_lean2.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "5";
      cellCountY = "3";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(greaser_lean2Animation) {
      imageMap = "greaser_lean2ImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14";
      animationTime = "1.25";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };   
   new t2dImageMapDatablock(bkgd_hometown_finalImageMap) {
      imageName = "~/data/images/bkgd_hometown_final.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };   
};