$managedDatablockSet = new SimSet() {
   canSaveDynamicFields = "1";
      setType = "Datablocks";
	  
   new t2dImageMapDatablock(char_conductor_angerImageMap) {
      imageName = "~/data/images/char_conductor_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_conductor_drinkImageMap) {
      imageName = "~/data/images/char_conductor_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_conductor_idleImageMap) {
      imageName = "~/data/images/char_conductor_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_trainman_angerImageMap) {
      imageName = "~/data/images/char_trainman_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_trainman_approveImageMap) {
      imageName = "~/data/images/char_trainman_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_trainman_drinkImageMap) {
      imageName = "~/data/images/char_trainman_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_trainman_idleImageMap) {
      imageName = "~/data/images/char_trainman_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_conductor_approveImageMap) {
      imageName = "~/data/images/char_conductor_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_conductor_angerAnimation) {
      imageMap = "char_conductor_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_conductor_drinkAnimation) {
      imageMap = "char_conductor_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_conductor_idleAnimation) {
      imageMap = "char_conductor_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_trainman_angerAnimation) {
      imageMap = "char_trainman_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.166667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_trainman_approveAnimation) {
      imageMap = "char_trainman_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_trainman_drinkAnimation) {
      imageMap = "char_trainman_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_trainman_idleAnimation) {
      imageMap = "char_trainman_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_conductor_approveAnimation) {
      imageMap = "char_conductor_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(char_bellhop_angerImageMap) {
      imageName = "~/data/images/char_bellhop_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_bellhop_approveImageMap) {
      imageName = "~/data/images/char_bellhop_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_bellhop_drinkImageMap) {
      imageName = "~/data/images/char_bellhop_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_bellhop_idleImageMap) {
      imageName = "~/data/images/char_bellhop_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_bellhop_angerAnimation) {
      imageMap = "char_bellhop_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_bellhop_approveAnimation) {
      imageMap = "char_bellhop_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_bellhop_drinkAnimation) {
      imageMap = "char_bellhop_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_bellhop_idleAnimation) {
      imageMap = "char_bellhop_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(char_trainwoman_idleImageMap) {
      imageName = "~/data/images/char_trainwoman_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_trainwoman_approveAnimation) {
      imageMap = "char_trainwoman_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_trainwoman_drinkAnimation) {
      imageMap = "char_trainwoman_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_trainwoman_angerAnimation) {
      imageMap = "char_trainwoman_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_trainwoman_idleAnimation) {
      imageMap = "char_trainwoman_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };

   new t2dImageMapDatablock(fx_train_handleImageMap) {
      imageName = "~/data/images/fx_train_handle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "11";
      cellCountY = "1";
      cellWidth = "42";
      cellHeight = "177";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(fx_train_handleAnimation) {
      imageMap = "fx_train_handleImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10";
      animationTime = "0.733333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(train_track_fxImageMap) {
      imageName = "~/data/images/train_track_fx.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "3";
      cellCountY = "1";
      cellWidth = "467";
      cellHeight = "257";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(train_track_fxAnimation) {
      imageMap = "train_track_fxImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.2";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(train_sky_fx2ImageMap) {
      imageName = "~/data/images/train_sky_fx2.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "3";
      cellCountY = "1";
      cellWidth = "461";
      cellHeight = "268";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(train_sky_fx2Animation) {
      imageMap = "train_sky_fx2ImageMap";
      animationFrames = "0 1 2";
      animationTime = "0.2";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(bellhop_bored2ImageMap) {
      imageName = "~/data/images/bellhop_bored2.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "5";
      cellCountY = "4";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(bellhop_bored2Animation) {
      imageMap = "bellhop_bored2ImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19";
      animationTime = "1.66667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };   
   new t2dImageMapDatablock(custom_train_seatImageMap) {
      imageName = "~/data/images/custom_train_seat.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(bkgd_train5ImageMap) {
      imageName = "~/data/images/bkgd_train5.jpg";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(bkgd_train_finalImageMap) {
      imageName = "~/data/images/bkgd_train_final.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };   
};