$managedDatablockSet = new SimSet() {
   canSaveDynamicFields = "1";
      setType = "Datablocks";
	  
   new t2dImageMapDatablock(char_mime_angerImageMap) {
      imageName = "~/data/images/char_mime_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_mime_approveImageMap) {
      imageName = "~/data/images/char_mime_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_mime_drinkImageMap) {
      imageName = "~/data/images/char_mime_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_mime_idleImageMap) {
      imageName = "~/data/images/char_mime_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_mime_angerAnimation) {
      imageMap = "char_mime_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_mime_approveAnimation) {
      imageMap = "char_mime_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_mime_drinkAnimation) {
      imageMap = "char_mime_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_mime_idleAnimation) {
      imageMap = "char_mime_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(char_frenchman_angerImageMap) {
      imageName = "~/data/images/char_frenchman_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_frenchman_approveImageMap) {
      imageName = "~/data/images/char_frenchman_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_frenchman_drinkImageMap) {
      imageName = "~/data/images/char_frenchman_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_frenchman_idleImageMap) {
      imageName = "~/data/images/char_frenchman_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_frenchwoman_angerImageMap) {
      imageName = "~/data/images/char_frenchwoman_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_frenchwoman_approveImageMap) {
      imageName = "~/data/images/char_frenchwoman_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_frenchwoman_drinkImageMap) {
      imageName = "~/data/images/char_frenchwoman_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_frenchwoman_idleImageMap) {
      imageName = "~/data/images/char_frenchwoman_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_moulin_angerImageMap) {
      imageName = "~/data/images/char_moulin_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_moulin_approveImageMap) {
      imageName = "~/data/images/char_moulin_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_moulin_drinkImageMap) {
      imageName = "~/data/images/char_moulin_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_moulin_idleImageMap) {
      imageName = "~/data/images/char_moulin_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_frenchman_angerAnimation) {
      imageMap = "char_frenchman_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_frenchman_approveAnimation) {
      imageMap = "char_frenchman_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_frenchman_drinkAnimation) {
      imageMap = "char_frenchman_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_frenchman_idleAnimation) {
      imageMap = "char_frenchman_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_frenchwoman_angerAnimation) {
      imageMap = "char_frenchwoman_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_frenchwoman_approveAnimation) {
      imageMap = "char_frenchwoman_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_frenchwoman_drinkAnimation) {
      imageMap = "char_frenchwoman_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_frenchwoman_idleAnimation) {
      imageMap = "char_frenchwoman_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_moulin_angerAnimation) {
      imageMap = "char_moulin_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.166667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_moulin_approveAnimation) {
      imageMap = "char_moulin_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_moulin_drinkAnimation) {
      imageMap = "char_moulin_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_moulin_idleAnimation) {
      imageMap = "char_moulin_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(char_critic_angerImageMap) {
      imageName = "~/data/images/char_critic_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_critic_approveImageMap) {
      imageName = "~/data/images/char_critic_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_critic_drinkImageMap) {
      imageName = "~/data/images/char_critic_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_critic_idleImageMap) {
      imageName = "~/data/images/char_critic_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };

   new t2dAnimationDatablock(char_critic_angerAnimation) {
      imageMap = "char_critic_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_critic_approveAnimation) {
      imageMap = "char_critic_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_critic_drinkAnimation) {
      imageMap = "char_critic_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_critic_idleAnimation) {
      imageMap = "char_critic_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(fx_chandelier2ImageMap) {
      imageName = "~/data/images/fx_chandelier2.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "189";
      cellHeight = "123";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(fx_chandelier2Animation) {
      imageMap = "fx_chandelier2ImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.6";
      animationCycle = "1";
      randomStart = "1";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(accordionist2ImageMap) {
      imageName = "~/data/images/accordionist2.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "5";
      cellCountY = "5";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(accordionist2Animation) {
      imageMap = "accordionist2ImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24";
      animationTime = "2.08333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };   
   new t2dImageMapDatablock(bkgd_france_finalImageMap) {
      imageName = "~/data/images/bkgd_france_final.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };   
};