$managedDatablockSet = new SimSet() {
   canSaveDynamicFields = "1";
      setType = "Datablocks";
	  
   new t2dImageMapDatablock(char_wolfman_angerImageMap) {
      imageName = "~/data/images/char_wolfman_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_wolfman_approveImageMap) {
      imageName = "~/data/images/char_wolfman_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_wolfman_drinkImageMap) {
      imageName = "~/data/images/char_wolfman_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_wolfman_idleImageMap) {
      imageName = "~/data/images/char_wolfman_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_wolfman_angerAnimation) {
      imageMap = "char_wolfman_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_wolfman_approveAnimation) {
      imageMap = "char_wolfman_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_wolfman_drinkAnimation) {
      imageMap = "char_wolfman_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_wolfman_idleAnimation) {
      imageMap = "char_wolfman_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(char_death_angerImageMap) {
      imageName = "~/data/images/char_death_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_death_approveImageMap) {
      imageName = "~/data/images/char_death_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_death_drinkImageMap) {
      imageName = "~/data/images/char_death_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_death_idleImageMap) {
      imageName = "~/data/images/char_death_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_pumpkinhead_angerImageMap) {
      imageName = "~/data/images/char_pumpkinhead_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_pumpkinhead_approveImageMap) {
      imageName = "~/data/images/char_pumpkinhead_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_pumpkinhead_drinkImageMap) {
      imageName = "~/data/images/char_pumpkinhead_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_pumpkinhead_idleImageMap) {
      imageName = "~/data/images/char_pumpkinhead_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_witch_angerImageMap) {
      imageName = "~/data/images/char_witch_anger.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "2";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_witch_approveImageMap) {
      imageName = "~/data/images/char_witch_approve.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_witch_drinkImageMap) {
      imageName = "~/data/images/char_witch_drink.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "6";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(char_witch_idleImageMap) {
      imageName = "~/data/images/char_witch_idle.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "7";
      cellCountY = "1";
      cellWidth = "98";
      cellHeight = "173";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(char_death_angerAnimation) {
      imageMap = "char_death_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_pumpkinhead_approveAnimation) {
      imageMap = "char_pumpkinhead_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_pumpkinhead_drinkAnimation) {
      imageMap = "char_pumpkinhead_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_pumpkinhead_idleAnimation) {
      imageMap = "char_pumpkinhead_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_pumpkinhead_angerAnimation) {
      imageMap = "char_pumpkinhead_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_death_approveAnimation) {
      imageMap = "char_death_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_death_drinkAnimation) {
      imageMap = "char_death_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_death_idleAnimation) {
      imageMap = "char_death_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_witch_angerAnimation) {
      imageMap = "char_witch_angerImageMap";
      animationFrames = "0 1";
      animationTime = "0.0666667";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_witch_approveAnimation) {
      imageMap = "char_witch_approveImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_witch_drinkAnimation) {
      imageMap = "char_witch_drinkImageMap";
      animationFrames = "0 1 2 3 4 5";
      animationTime = "0.5";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(char_witch_idleAnimation) {
      imageMap = "char_witch_idleImageMap";
      animationFrames = "0 1 2 3 4 5 6";
      animationTime = "0.583333";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(ghostImageMap) {
      imageName = "~/data/images/ghost.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "4";
      cellCountY = "4";
      cellWidth = "121";
      cellHeight = "176";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(ghostAnimation) {
      imageMap = "ghostImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15";
      animationTime = "1.33333";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(blinkImageMap) {
      imageName = "~/data/images/blink.png";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "1";
      cellCountY = "1";
      cellWidth = "23";
      cellHeight = "8";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(fx_jackolanternImageMap) {
      imageName = "~/data/images/fx_jackolantern.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "4";
      cellCountY = "1";
      cellWidth = "64";
      cellHeight = "70";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(swing_lamp1ImageMap) {
      imageName = "~/data/images/swing_lamp1.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "11";
      cellCountY = "1";
      cellWidth = "45";
      cellHeight = "131";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dImageMapDatablock(swing_lamp2ImageMap) {
      imageName = "~/data/images/swing_lamp2.PNG";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "11";
      cellCountY = "1";
      cellWidth = "47";
      cellHeight = "185";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };
   new t2dAnimationDatablock(fx_jackolanternAnimation) {
      imageMap = "fx_jackolanternImageMap";
      animationFrames = "0 1 2 3";
      animationTime = "0.4";
      animationCycle = "1";
      randomStart = "1";
      startFrame = "0";
      animationPingPong = "0";
      animationReverse = "0";
   };   
   new t2dAnimationDatablock(swing_lamp1Animation) {
      imageMap = "swing_lamp1ImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10";
      animationTime = "1.1";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };
   new t2dAnimationDatablock(swing_lamp2Animation) {
      imageMap = "swing_lamp2ImageMap";
      animationFrames = "0 1 2 3 4 5 6 7 8 9 10";
      animationTime = "1.1";
      animationCycle = "1";
      randomStart = "0";
      startFrame = "0";
      animationPingPong = "1";
      animationReverse = "0";
   };
   new t2dImageMapDatablock(bkgd_haunted_finalImageMap) {
      imageName = "~/data/images/bkgd_haunted_final.png";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "1";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
      force16Bit = "0";
   };   
};